### ISSUE TITLE
Email regex (and the decrypted validators.txt is gibberish)

### ISSUE THREAD

**Issue by misterfifths** [learn-co-curriculum/validated-signup#2]
Looks like the encoding is busted or something?

But regardless, I have philosophical hangups about trying to strictly validate an email address. The RFC is shockingly complicated, and a proven-correct regex is ~100 lines long: http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html.

I usually use `[^@ ]+@[^. ]+\.[^ ]+` -- "something, then a '@', then some more stuff, then a '.', then some more stuff". Yes, that allows "a@b.c", but is that really any worse than "nobody@notanemail.com"? The real goal in "validating" emails is to prevent user typos -- you can't ensure the actual address is valid without sending an email to it.

**Comment by AnnJohn** [comment]
Iceboxing for now
